name: CI/CD

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      my-flask-app:
        image: my-flask-app
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000/ || exit 1"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build the application
        run: |
          echo "Building the application..."
          docker build -t my-flask-app .

      - name: Run tests
        run: |
          echo "Running tests..."
          curl --fail http://localhost:5000/ || exit 1
