name: CI/CD

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build the application
        run: |
          echo "Building the application..."
          docker build -t sasiska228/test_ci_cd:latest .

  runing_app:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Start the application
      run: |
        echo "Starting the application..."
        docker run -p 5000:5000 -d --name my-running-flask-app sasiska228/test_ci_cd:latest

    - name: Run tests
      run: |
        echo "Running tests..."
        curl --fail http://localhost:5000/ || exit 1
  pushing:
    needs: [runing_app, build]
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pushing
      run: |
          docker push sasiska228/test_ci_cd:latest
        


