name: CI/CD

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build the application
        run: |
          docker build -t sasiska228/test_ci_cd:latest .

      - name: Start the application
        run: |
          docker run -p 5000:5000 -d --name my-running-flask-app sasiska228/test_ci_cd:latest

      - name: Wait for the application to start
        run: sleep 10  # Задержка для ожидания запуска приложения

      - name: Run tests
        run: |
          echo "Running tests..."
          curl --fail http://localhost:5000/ || exit 1

      - name: Stop and remove the application
        run: |
          echo "Stopping and removing the application..."
          docker stop my-running-flask-app || true
          docker rm my-running-flask-app || true

  pushing:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build the application
      run: |
        echo "Building the application..."
        docker build -t sasiska228/test_ci_cd:latest .
    - name: Pushing
      run: |
          docker push sasiska228/test_ci_cd:latest
        
  restarting_app:
    needs: [build, pushing]
    runs-on: self-hosted
    steps:
    - name: Pull image
      run: |
        docker pull sasiska228/test_ci_cd:latest

    - name: Reloading app
      run: |
        docker ps -q -f name=my-running-flask-app && \
        docker stop my-running-flask-app && \
        docker rm my-running-flask-app && \
        docker start my-running-flask-app || \
        docker run -p 5000:5000 -d --name my-running-flask-app sasiska228/test_ci_cd:latest

    - name: Wait for the application to start
      run: sleep 10  # Задержка для ожидания запуска приложения

    - name: Run tests
      run: |
        echo "Running tests..."
        curl --fail http://localhost:5000/ || exit 1


        
