name: CI/CD

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build the application
        run: |
          echo "Building the application..."
          docker build -t my-flask-app .

      - name: Start the application
        run: |
          echo "Starting the application..."
          docker run -d --name my-flask-app -p 5000:5000 --health-cmd="curl --fail http://localhost:5000/ || exit 1" --health-interval=30s --health-timeout=10s --health-retries=3 my-flask-app

      - name: Run tests
        run: |
          echo "Running tests..."
          curl --fail http://localhost:5000/ || exit 1

      - name: Stop the application
        run: |
          echo "Stopping the application..."
          docker stop my-flask-app
          docker rm my-flask-app
